version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  mongo:
    image: mongo
    container_name: kapp-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./server
    container_name: kapp-backend
    restart: always
    env_file: ./server/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build: ./client
    container_name: kapp-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  jenkins_home:
  mongo-data:
